import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import {
  fetchChartData,
  fetchAllRSIData,
  fetchLivePlusIndicatorData,
  fetchTradeData,
} from "./stockAPI";

const initialState = {
  allRSIData: {},
  chartData: {},
  livePlusIndicatorData: {},
  tradeData: {},
};

export const getAllRSIDataAsync = createAsyncThunk(
  "stock/fetchAllRSIData",
  async (amount) => {
    const response = await fetchAllRSIData(amount);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const getChartDataAsync = createAsyncThunk(
  "stock/fetchChartData",
  async (amount) => {
    const response = await fetchChartData(amount);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const getLivePlusIndicatorData = createAsyncThunk(
  "stock/getLivePlusIndicatorData",
  async (amount) => {
    const response = await fetchLivePlusIndicatorData();
    // The value we return becomes the `fulfilled` action payload
    console.log("fetchLivePlusIndicatorData response", response);
    return response.data;
  }
);

export const getTradeDataAsync = createAsyncThunk(
  "stock/getTradeData",
  async (amount) => {
    const response = await fetchTradeData();
    // The value we return becomes the `fulfilled` action payload
    console.log("fetchLivePlusIndicatorData response", response);
    return response.data;
  }
);

export const stockSlice = createSlice({
  name: "stocks",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    sellStock: (state) => {
      console.log("sell Stock");
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getAllRSIDataAsync.pending, (state) => {
        //console.log("getting trade data");
        state.status = "loading";
      })
      .addCase(getAllRSIDataAsync.fulfilled, (state, action) => {
        //console.log("action.payload", action.payload);
        state.allRSIData = action.payload;
      })
      .addCase(getChartDataAsync.pending, (state) => {
        //console.log("getting live data");
        state.status = "loading";
      })
      .addCase(getChartDataAsync.fulfilled, (state, action) => {
        //console.log(" getChartDataAsync action.payload", action.payload);
        state.chartData = action.payload;
      })
      .addCase(getLivePlusIndicatorData.fulfilled, (state, action) => {
        //console.log("getLivePlusIndicatorData action.payload", action.payload);
        state.livePlusIndicatorData = action.payload;
      })
      .addCase(getTradeDataAsync.fulfilled, (state, action) => {
        //console.log("getTradeData action.payload", action.payload);
        state.tradeData = action.payload;
      });
  },
});

export const { sellStock } = stockSlice.actions;

export const selectAllRSIData = (state) => state.stocks.allRSIData;
export const selectChartData = (state) => state.stocks.chartData;
export const selectLivePlusIndicatorData = (state) =>
  state.stocks.livePlusIndicatorData;
export const selectTradeData = (state) => state.stocks.tradeData;

export default stockSlice.reducer;
