module.exports = {
  nseBaseURL: "https://www.nseindia.com/",
  nseDataURL: "https://www.nseindia.com/api/quote-equity?symbol={0}",
  moneyControlSMAEMAUrl:
    "https://priceapi.moneycontrol.com/pricefeed/techindicator/D/{0}?fields=sentiments,pivotLevels,sma,ema",
  headers: {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "accept-language": "en,gu;q=0.9,hi;q=0.8",
    "accept-encoding": "gzip, deflate, br",
  },
  nseWaitTime: 1000,
  waitTime: 500,
  allStocks1: [
    {
      symbol: "PIIND",
      mcScid: "PII",
      mcScdid: "PII",
      angelName: "PI Industries",
      sector: "Agriculture",
    },

    {
      symbol: "UPL",
      mcScid: "SI10",
      mcScdid: "UP04",
      angelName: "UPL",
      sector: "Agriculture",
    },
  ],
  allStocks: [
    {
      symbol: "PIIND",
      mcScid: "PII",
      mcScdid: "PII",
      angelName: "PI Industries",
      sector: "Agriculture",
    },

    {
      symbol: "UPL",
      mcScid: "SI10",
      mcScdid: "UP04",
      angelName: "UPL",
      sector: "Agriculture",
    },
    {
      symbol: "COROMANDEL",
      mcScid: "CF06",
      mcScdid: "CI45",
      sector: "Agriculture",
    },
    {
      symbol: "SUMICHEM",
      mcScid: "SUMIC54292",
      mcScdid: "SUMIC54292",
      sector: "Agriculture",
    },

    {
      symbol: "FACT",
      mcScid: "FCT",
      mcScdid: "FCT",
      angelName: "Fertilisers & Chemicals Travancore",
      sector: "Agriculture",
    },

    {
      symbol: "BAYERCROP",
      mcScid: "HSA01",
      mcScdid: "BC12",
      angelName: "BAYER CORP SCI.",
      sector: "Agriculture",
    },

    {
      symbol: "CHAMBLFERT",
      mcScid: "CFC",
      mcScdid: "CFC",
      angelName: "Chambal Fertilisers & Chemicals",
      sector: "Agriculture",
    },

    {
      symbol: "BASF",
      mcScid: "BAS",
      mcScdid: "BAS",
      angelName: "BASF India",
      sector: "Agriculture",
    },

    {
      symbol: "GNFC",
      mcScid: "GNV",
      mcScdid: "GNV",
      angelName: "Gujarat Narmada Valley Fertilizers & Chemicals",
      sector: "Agriculture",
    },

    {
      symbol: "RALLIS",
      mcScid: "RI03",
      mcScdid: "RI03",
      angelName: "RALLIS INDIA",
      sector: "Agriculture",
    },
    {
      symbol: "BBTC",
      mcScid: "BBT",
      mcScdid: "BBT",
      angelName: "BOMBAY BURMAH",
      sector: "Agriculture",
    },
    {
      symbol: "TITAN",
      mcScid: "TI01",
      mcScdid: "TI01",
      sector: "Apparel & Accessories",
    },
    {
      symbol: "RELAXO",
      mcScid: "RF07",
      mcScdid: "RF07",
      sector: "Apparel & Accessories",
    },
    {
      symbol: "RAJESHEXPO",
      mcScid: "RE07",
      mcScdid: "RE07",
      angelName: "Rajesh Exports Ltd.",
      sector: "Apparel & Accessories",
    },
    {
      symbol: "KALYANKJIL",
      mcScid: "KJI01",
      mcScdid: "KJI01",
      angelName: "Kalyan Jewellers India",
      sector: "Apparel & Accessories",
    },
    {
      symbol: "CAMPUS",
      mcScid: "CA08",
      mcScdid: "CA07",
      angelName: "Campus Activewear Ltd.",
      sector: "Apparel & Accessories",
    },
    {
      symbol: "MARUTI",
      mcScid: "MU01",
      mcScdid: "MS24",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "TATAMOTORS",
      mcScid: "TEL",
      mcScdid: "TM03",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "TATAMTRDVR",
      mcScid: "TMD",
      mcScdid: "TATAM57000",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "M&M",
      mcScid: "MM",
      mcScdid: "MM",
      angelName: "M & M",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "BAJAJ-AUTO",
      mcScid: "BA06",
      mcScdid: "BA10",
      angelName: "BAJAJ AUTO",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "EICHERMOT",
      mcScid: "EM",
      mcScdid: "EM",
      angelName: "EICHER MOTORS",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "TVSMOTOR",
      mcScid: "TVS",
      mcScdid: "TVS",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "HEROMOTOCO",
      mcScid: "HHM",
      mcScdid: "HHM",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "TIINDIA",
      mcScid: "TIIND54076",
      mcScdid: "TIIND54076",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "BOSCHLTD",
      mcScid: "MIC",
      mcScdid: "B05",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "MOTHERSON",
      mcScid: "MSS01",
      mcScdid: "MSS01",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "SCHAEFFLER",
      mcScid: "FPB",
      mcScdid: "FAG",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "BALKRISIND",
      mcScid: "BI03",
      mcScdid: "BI03",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "ASHOKLEY",
      mcScid: "AL",
      mcScdid: "AL",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "MRF",
      mcScid: "MRF",
      mcScdid: "MRF",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "UNOMINDA",
      mcScid: "MI44",
      mcScdid: "MI4",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "SONACOMS",
      mcScid: "SBP04",
      mcScdid: "SBP04",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "ESCORTS",
      mcScid: "E",
      mcScdid: "E",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "TIMKEN",
      mcScid: "TT04",
      mcScdid: "TI23",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "APOLLOTYRE",
      mcScid: "AT",
      mcScdid: "AT14",
      angelName: "APOLLO TYRES",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "SKFINDIA",
      mcScid: "SKF",
      mcScdid: "SKF01",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "ENDURANCE",
      mcScid: "ET04",
      mcScdid: "ET01",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "ZFCVINDIA",
      mcScid: "WAB",
      mcScdid: "WAB",
      sector: "Automobile & Ancillaries",
    },
    {
      symbol: "HDFCBANK",
      mcScid: "HDF01",
      mcScdid: "HDF01",
      sector: "Banking",
    },
    {
      symbol: "ICICIBANK",
      mcScid: "ICI02",
      mcScdid: "ICI02",
      sector: "Banking",
    },
    {
      symbol: "SBIN",
      mcScid: "SBI",
      mcScdid: "SBI",
      sector: "Banking",
    },
    {
      symbol: "KOTAKBANK",
      mcScid: "KMF",
      mcScdid: "KMB",
      angelName: "KOTAK MAH. BANK",
      sector: "Banking",
    },
    {
      symbol: "AXISBANK",
      mcScid: "UTI10",
      mcScdid: "AB16",
      sector: "Banking",
    },
    {
      symbol: "INDUSINDBK",
      mcScid: "IIB",
      mcScdid: "IIB",
      sector: "Banking",
    },
    {
      symbol: "BANKBARODA",
      mcScid: "BOB",
      mcScdid: "BOB",
      sector: "Banking",
    },
    {
      symbol: "IDBI",
      mcScid: "IDB",
      mcScdid: "IDB05",
      angelName: "IDBI",
      sector: "Banking",
    },
    {
      symbol: "PNB",
      mcScid: "PNB05",
      mcScdid: "PNB05",
      sector: "Banking",
    },
    {
      symbol: "CANBK",
      mcScid: "CB06",
      mcScdid: "CB06",
      sector: "Banking",
    },
    {
      symbol: "AUBANK",
      mcScid: "ASF03",
      mcScdid: "ASF02",
      sector: "Banking",
    },
    {
      symbol: "UNIONBANK",
      mcScid: "UBI01",
      mcScdid: "UBI01",
      angelName: "UNION BANK",
      sector: "Banking",
    },
    {
      symbol: "IDFCFIRSTB",
      mcScid: "IDF01",
      mcScdid: "IDF01",
      angelName: "IDFC FIRST BANK",
      sector: "Banking",
    },
    {
      symbol: "IOB",
      mcScid: "IOB",
      mcScdid: "IOB",
      sector: "Banking",
    },
    {
      symbol: "YESBANK",
      mcScid: "YB",
      mcScdid: "YB",
      angelName: "YES BANK",
      sector: "Banking",
    },
    {
      symbol: "BANDHANBNK",
      mcScid: "BB09",
      mcScdid: "BB09",
      sector: "Banking",
    },
    {
      symbol: "INDIANB",
      mcScid: "IB04",
      mcScdid: "IB04",
      sector: "Banking",
    },
    {
      symbol: "UCOBANK",
      mcScid: "UCO",
      mcScdid: "UCO",
      sector: "Banking",
    },
    {
      symbol: "BANKINDIA",
      mcScid: "BOI",
      mcScdid: "BOI",
      sector: "Banking",
    },
    {
      symbol: "FEDERALBNK",
      mcScid: "FB",
      mcScdid: "FB",
      sector: "Banking",
    },
    {
      symbol: "CENTRALBK",
      mcScid: "CBO01",
      mcScdid: "CBO01",
      sector: "Banking",
    },
    {
      symbol: "MAHABANK",
      mcScid: "BM05",
      mcScdid: "BM05",
      angelName: "Bank of Maha",
      sector: "Banking",
    },
    {
      symbol: "DMART",
      mcScid: "AS28",
      mcScdid: "AS19",
      sector: "Consumer Durables",
      angelName: "Avenue Supermarts Ltd",
    },
    {
      symbol: "ZOMATO",
      mcScid: "Z01",
      mcScdid: "Z",
      angelName: "ZOMATO LTD",
      sector: "Consumer Durables",
    },
    {
      symbol: "TRENT",
      mcScid: "L",
      mcScdid: "T04",
      sector: "Consumer Durables",
    },
    {
      symbol: "NYKAA",
      mcScid: "FEV",
      mcScdid: "FEV",
      sector: "Consumer Durables",
    },
    {
      symbol: "HONAUT",
      mcScid: "TH",
      mcScdid: "HA04",
      sector: "Consumer Durables",
    },
    {
      symbol: "VOLTAS",
      mcScid: "V",
      mcScdid: "V",
      sector: "Consumer Durables",
    },
    {
      symbol: "AMBER",
      mcScid: "AEI01",
      mcScdid: "AEI01",
      sector: "Consumer Durables",
    },
    {
      symbol: "METROBRAND",
      mcScid: "MB05",
      mcScdid: "MB06",
      sector: "Consumer Durables",
    },
    {
      symbol: "DIXON",
      mcScid: "DT07",
      mcScdid: "DT07",
      sector: "Consumer Durables",
    },
    {
      symbol: "BATAINDIA",
      mcScid: "BI01",
      mcScdid: "BI01",
      sector: "Consumer Durables",
    },
    {
      symbol: "ABFRL",
      mcScid: "PFR",
      mcScdid: "PFR",
      angelName: "ADITYA BIR. FAS.",
      sector: "Consumer Durables",
    },
    {
      symbol: "WHIRLPOOL",
      mcScid: "WI",
      mcScdid: "WI",
      angelName: "Whirlpool Of India Ltd",
      sector: "Consumer Durables",
    },
    {
      symbol: "CROMPTON",
      mcScid: "CGC01",
      mcScdid: "CGC01",
      sector: "Consumer Durables",
    },
    {
      symbol: "INDIAMART",
      mcScid: "II22",
      mcScdid: "II12",
      sector: "Consumer Durables",
    },
    {
      symbol: "BLUESTARCO",
      mcScid: "BS",
      mcScdid: "BS",
      sector: "Consumer Durables",
      angelName: "Blue Star",
    },
    {
      symbol: "BAJAJELEC",
      mcScid: "BE",
      mcScdid: "BE",
      angelName: "BAJAJ ELECTRIC",
      sector: "Consumer Durables",
    },
    {
      symbol: "TTKPRESTIG",
      mcScid: "TTK02",
      mcScdid: "TTK02",
      sector: "Consumer Durables",
    },
    {
      symbol: "ASIANPAINT",
      mcScid: "API",
      mcScdid: "AP31",
      sector: "Derived Materials",
    },
    {
      symbol: "JSWSTEEL",
      mcScid: "JVS",
      mcScdid: "JSW01",
      sector: "Derived Materials",
    },
    {
      symbol: "TATASTEEL",
      mcScid: "TIS",
      mcScdid: "TIS",
      sector: "Derived Materials",
    },
    {
      symbol: "SHYAMMETL",
      mcScid: "SME05",
      mcScdid: "SME05",
      angelName: "SHYAM METALICS",
      sector: "Derived Materials",
    },
    {
      symbol: "WELCORP",
      mcScid: "WGS",
      mcScdid: "WGS",
      angelName: "Welspun Corp Ltd.",
      sector: "Derived Materials",
    },
    {
      symbol: "BERGEPAINT",
      mcScid: "BPI02",
      mcScdid: "BPI02",
      sector: "Derived Materials",
    },
    {
      symbol: "ASTRAL",
      mcScid: "APT02",
      mcScdid: "APT02",
      sector: "Derived Materials",
    },
    {
      symbol: "BHARATFORG",
      mcScid: "BFC",
      mcScdid: "BF03",
      sector: "Derived Materials",
    },
    {
      symbol: "SUPREMEIND",
      mcScid: "SI48",
      mcScdid: "SI48",
      sector: "Derived Materials",
    },
    {
      symbol: "SAIL",
      mcScid: "SAI",
      mcScdid: "SAI",
      sector: "Derived Materials",
    },
    {
      symbol: "APLAPOLLO",
      mcScid: "BT09",
      mcScdid: "BT09",
      sector: "Derived Materials",
    },
    {
      symbol: "AIAENG",
      mcScid: "AIE01",
      mcScdid: "AIE01",
      sector: "Derived Materials",
    },
    {
      symbol: "MSUMI",
      mcScid: "MSW",
      mcScdid: "MSW",
      sector: "Derived Materials",
    },
    {
      symbol: "SUNDRMFAST",
      mcScid: "SF",
      mcScdid: "SF23",
      sector: "Derived Materials",
    },
    {
      symbol: "JSL",
      mcScid: "JS07",
      mcScdid: "JSL01",
      sector: "Derived Materials",
    },
    {
      symbol: "GRINDWELL",
      mcScid: "GN",
      mcScdid: "GN",
      sector: "Derived Materials",
    },
    {
      symbol: "KANSAINER",
      mcScid: "GNP",
      mcScdid: "KNP",
      angelName: "KANSAI NEROLAC",
      sector: "Derived Materials",
    },
    {
      symbol: "CARBORUNIV",
      mcScid: "CU",
      mcScdid: "CU",
      sector: "Derived Materials",
    },
    {
      symbol: "KAJARIACER",
      mcScid: "KC06",
      mcScdid: "KC06",
      sector: "Derived Materials",
    },
    {
      symbol: "CIEINDIA",
      mcScid: "MAS",
      mcScdid: "MF19",
      sector: "Derived Materials",
    },
    {
      symbol: "RATNAMANI",
      mcScid: "RMT",
      mcScdid: "RMT",
      sector: "Derived Materials",
    },
    {
      symbol: "NATIONALUM",
      mcScid: "NAC",
      mcScdid: "NAC",
      sector: "Derived Materials",
    },

    {
      symbol: "NSLNISP",
      mcScid: "NS16",
      mcScdid: "NS15",
      sector: "Derived Materials",
    },
    {
      symbol: "CENTURYPLY",
      mcScid: "CP9",
      mcScdid: "CP9",
      sector: "Derived Materials",
    },
    {
      symbol: "CASTROLIND",
      mcScid: "CI01",
      mcScdid: "CI01",
      angelName: "CASTROL INDIA",
      sector: "Derived Materials",
    },
    {
      symbol: "ASAHIINDIA",
      mcScid: "AIS",
      mcScdid: "AIG01",
      sector: "Derived Materials",
    },
    {
      symbol: "AKZOINDIA",
      mcScid: "ICI",
      mcScdid: "ICI",
      angelName: "AKZO NOBEL",
      sector: "Derived Materials",
    },
    {
      symbol: "FINPIPE",
      mcScid: "FI",
      mcScdid: "FI",
      sector: "Derived Materials",
    },
    {
      symbol: "RELIANCE",
      mcScid: "RI",
      mcScdid: "RI",
      sector: "Energy",
    },
    {
      symbol: "ONGC",
      mcScid: "ONG",
      mcScdid: "ONG",
      sector: "Energy",
    },
    {
      symbol: "NTPC",
      mcScid: "NTP",
      mcScdid: "NTP",
      sector: "Energy",
    },
    {
      symbol: "POWERGRID",
      mcScid: "PGC",
      mcScdid: "PGC",
      sector: "Energy",
    },
    {
      symbol: "ADANIGREEN",
      mcScid: "ADANI54145",
      mcScdid: "ADANI54145",
      sector: "Energy",
    },
    {
      symbol: "IOC",
      mcScid: "IOC",
      mcScdid: "IOC",
      sector: "Energy",
    },
    {
      symbol: "ADANIPOWER",
      mcScid: "AP26",
      mcScdid: "AP11",
      sector: "Energy",
    },
    {
      symbol: "ADANITRANS",
      mcScid: "AT18",
      mcScdid: "AT22",
      sector: "Energy",
    },
    {
      symbol: "BPCL",
      mcScid: "BPC",
      mcScdid: "BPC",
      angelName: "B P C L",
      sector: "Energy",
    },
    {
      symbol: "ATGL",
      mcScid: "ADG01",
      mcScdid: "ADG01",
      sector: "Energy",
    },
    {
      symbol: "TATAPOWER",
      mcScid: "TPC",
      mcScdid: "TPC",
      sector: "Energy",
    },
    {
      symbol: "GAIL",
      mcScid: "GAI",
      mcScdid: "GAI",
      sector: "Energy",
    },
    {
      symbol: "NHPC",
      mcScid: "N07",
      mcScdid: "N07",
      sector: "Energy",
    },
    {
      symbol: "JSWENERGY",
      mcScid: "JE02",
      mcScdid: "JE01",
      sector: "Energy",
    },
    {
      symbol: "HINDPETRO",
      mcScid: "HPC",
      mcScdid: "HPC",
      angelName: "H P C L",
      sector: "Energy",
    },
    {
      symbol: "LINDEINDIA",
      mcScid: "BOC",
      mcScdid: "BOC",
      sector: "Energy",
    },
    {
      symbol: "PETRONET",
      mcScid: "PLN",
      mcScdid: "PLN",
      sector: "Energy",
    },
    {
      symbol: "GUJGASLTD",
      mcScid: "GGC",
      mcScdid: "GGC",
      sector: "Energy",
    },
    {
      symbol: "IGL",
      mcScid: "IG04",
      mcScdid: "IG04",
      angelName: "INDRAPRASTHA G..",
      sector: "Energy",
    },
    {
      symbol: "TORNTPOWER",
      mcScid: "TP13",
      mcScdid: "TP14",
      angelName: "TORRENT POWER",
      sector: "Energy",
    },
    {
      symbol: "OIL",
      mcScid: "OI13",
      mcScdid: "OI13",
      sector: "Energy",
    },
    {
      symbol: "EXIDEIND",
      mcScid: "EI",
      mcScdid: "EI",
      angelName: "EXIDE INDS.",
      sector: "Energy",
    },
    {
      symbol: "GSPL",
      mcScid: "GSP02",
      mcScdid: "GSP02",
      sector: "Energy",
      angelName: "Gujarat State Petronet Ltd",
    },
    {
      symbol: "SJVN",
      mcScid: "S14",
      mcScdid: "S11",
      sector: "Energy",
    },
    {
      symbol: "NLCINDIA",
      mcScid: "NLC",
      mcScdid: "NLC",
      sector: "Energy",
    },
    {
      symbol: "IEX",
      mcScid: "IEE",
      mcScdid: "IEE",
      sector: "Energy",
    },
    {
      symbol: "MRPL",
      mcScid: "MRP",
      mcScdid: "MRP",
      sector: "Energy",
    },
    {
      symbol: "AMARAJABAT",
      mcScid: "ARB",
      mcScdid: "ARB",
      angelName: "AMARA RAJA BATT.",
      sector: "Energy",
    },
    {
      symbol: "MGL",
      mcScid: "MG02",
      mcScdid: "MG02",
      angelName: "MAHANAGAR GAS",
      sector: "Energy",
    },
    {
      symbol: "CESC",
      mcScid: "CES",
      mcScdid: "CES",
      sector: "Energy",
    },
    {
      symbol: "MCX",
      mcScid: "MCE",
      mcScdid: "MCE",
      sector: "Financials",
    },
    {
      symbol: "MOTILALOFS",
      mcScid: "MOF01",
      mcScdid: "MOF01",
      sector: "Financials",
    },
    {
      symbol: "BAJFINANCE",
      mcScid: "BAF",
      mcScdid: "BAF",
      sector: "Financials",
    },
    {
      symbol: "UTIAMC",
      mcScid: "UA03",
      mcScdid: "UA04",
      sector: "Financials",
    },
    {
      symbol: "LICI",
      mcScid: "LIC09",
      mcScdid: "LIC09",
      angelName: "LIC India",
      sector: "Financials",
    },
    {
      symbol: "ADANIENT",
      mcScid: "AE01",
      mcScdid: "AE13",
      sector: "Financials",
    },
    {
      symbol: "BAJAJFINSV",
      mcScid: "BF04",
      mcScdid: "BF04",
      sector: "Financials",
    },
    {
      symbol: "HDFCLIFE",
      mcScid: "HSL01",
      mcScdid: "HSL01",
      sector: "Financials",
    },
    {
      symbol: "SBILIFE",
      mcScid: "SLI03",
      mcScdid: "SLI03",
      sector: "Financials",
    },
    {
      symbol: "SBICARD",
      mcScid: "SCP03",
      mcScdid: "SCP02",
      sector: "Financials",
    },
    {
      symbol: "CHOLAFIN",
      mcScid: "CIF01",
      mcScdid: "CDB",
      sector: "Financials",
    },
    {
      symbol: "BAJAJHLDNG",
      mcScid: "BA",
      mcScdid: "BHI",
      sector: "Financials",
    },
    {
      symbol: "ICICIPRULI",
      mcScid: "IPL01",
      mcScdid: "IPL01",
      sector: "Financials",
    },
    {
      symbol: "ICICIGI",
      mcScid: "ILG",
      mcScdid: "ILG",
      sector: "Financials",
    },
    {
      symbol: "SHRIRAMFIN",
      mcScid: "STF",
      mcScdid: "STF",
      sector: "Financials",
    },
    {
      symbol: "PFC",
      mcScid: "PFC02",
      mcScdid: "PFC02",
      sector: "Financials",
    },
    {
      symbol: "MUTHOOTFIN",
      mcScid: "MF19",
      mcScdid: "MF10",
      sector: "Financials",
    },
    {
      symbol: "HDFCAMC",
      mcScid: "HAM02",
      mcScdid: "HAM02",
      angelName: "HDFC AMC",
      sector: "Financials",
    },
    {
      symbol: "IRFC",
      mcScid: "IRF",
      mcScdid: "IRF",
      angelName: "I R F C",
      sector: "Financials",
    },
    {
      symbol: "ABCAPITAL",
      mcScid: "ABC07",
      mcScdid: "ABC9",
      sector: "Financials",
    },
    {
      symbol: "RECLTD",
      mcScid: "REC02",
      mcScdid: "REC02",
      angelName: "R E C LTD",
      sector: "Financials",
    },
    {
      symbol: "M&MFIN",
      mcScid: "MMF04",
      mcScdid: "MMF04",
      sector: "Financials",
    },
    {
      symbol: "GICRE",
      mcScid: "GIC12",
      mcScdid: "GIC12",
      angelName: "GENERAL INS CORP OF INDIA",
      sector: "Financials",
    },
    {
      symbol: "STARHEALTH",
      mcScid: "SHA",
      mcScdid: "SHA",
      sector: "Financials",
    },
    {
      symbol: "SUNDARMFIN",
      mcScid: "SF20",
      mcScdid: "SF20",
      sector: "Financials",
    },
    {
      symbol: "CRISIL",
      mcScid: "CRI",
      mcScdid: "CRI",
      sector: "Financials",
    },
    {
      symbol: "POONAWALLA",
      mcScid: "ML07",
      mcScdid: "MF20",
      sector: "Financials",
    },
    {
      symbol: "L&TFH",
      mcScid: "LFH",
      mcScdid: "LFH",
      sector: "Financials",
    },
    {
      symbol: "MFSL",
      mcScid: "MI",
      mcScdid: "MI",
      sector: "Financials",
    },
    {
      symbol: "LICHSGFIN",
      mcScid: "LIC",
      mcScdid: "LIC",
      angelName: "LIC HOUSING FIN.",
      sector: "Financials",
    },
    {
      symbol: "CREDITACC",
      mcScid: "CG02",
      mcScdid: "CG03",
      sector: "Financials",
    },
    {
      symbol: "NIACL",
      mcScid: "NIA",
      mcScdid: "NIA",
      sector: "Financials",
    },
    {
      symbol: "PEL",
      mcScid: "NP07",
      mcScdid: "PH05",
      sector: "Financials",
    },
    {
      symbol: "IIFL",
      mcScid: "II15",
      mcScdid: "II15",
      sector: "Financials",
    },
    {
      symbol: "ISEC",
      mcScid: "ISL03",
      mcScdid: "ISL04",
      angelName: "ICICI Securities",
      sector: "Financials",
    },
    {
      symbol: "FIVESTAR",
      mcScid: "FBF",
      mcScdid: "FBF",
      sector: "Financials",
    },
    {
      symbol: "IDFC",
      mcScid: "IDF",
      mcScdid: "IDF",
      sector: "Financials",
    },
    {
      symbol: "NAM-INDIA",
      mcScid: "RNL",
      mcScdid: "RNL",
      sector: "Financials",
    },
    {
      symbol: "CHOLAHLDNG",
      mcScid: "TII",
      mcScdid: "TII",
      sector: "Financials",
    },
    {
      symbol: "360ONE",
      mcScid: "IIFLW54277",
      mcScdid: "IIFLW54277",
      angelName: "360 ONE WAM Ltd.",
      sector: "Financials",
    },
    {
      symbol: "CGCL",
      mcScid: "DSL01",
      mcScdid: "MMF05",
      sector: "Financials",
    },
    {
      symbol: "REDINGTON",
      mcScid: "RI37",
      mcScdid: "RI37",
      sector: "Financials",
    },
    {
      symbol: "PNBHOUSING",
      mcScid: "PHF",
      mcScdid: "PHF",
      sector: "Financials",
    },
    {
      symbol: "APTUS",
      mcScid: "AVH",
      mcScdid: "AVH",
      sector: "Financials",
    },
    {
      symbol: "HUDCO",
      mcScid: "HUD",
      mcScdid: "HUD",
      sector: "Financials",
    },
    {
      symbol: "TATAINVEST",
      mcScid: "TIC",
      mcScdid: "TIC",
      sector: "Financials",
    },
    {
      symbol: "ANGELONE",
      mcScid: "ABL03",
      mcScdid: "ABL03",
      sector: "Financials",
    },
    {
      symbol: "AAVAS",
      mcScid: "AF32",
      mcScdid: "AF17",
      sector: "Financials",
    },
    {
      symbol: "CDSL",
      mcScid: "CDS",
      mcScdid: "CDS",
      angelName: "C D S L",
      sector: "Financials",
    },
    {
      symbol: "HINDUNILVR",
      mcScid: "HL",
      mcScdid: "HU",
      angelName: "HIN. UNILEVER",
      sector: "FMCG",
    },
    {
      symbol: "ITC",
      mcScid: "ITC",
      mcScdid: "ITC",
      sector: "FMCG",
    },
    {
      symbol: "JYOTHYLAB",
      mcScid: "JL",
      mcScdid: "JL",
      sector: "FMCG",
    },
    {
      symbol: "VSTIND",
      mcScid: "VST",
      mcScdid: "VST",
      angelName: "VST INDUSTRIES",
      sector: "FMCG",
    },
    {
      symbol: "NESTLEIND",
      mcScid: "NI",
      mcScdid: "NI",
      sector: "FMCG",
    },
    {
      symbol: "BRITANNIA",
      mcScid: "BI",
      mcScdid: "BI",
      sector: "FMCG",
    },
    {
      symbol: "VBL",
      mcScid: "VB05",
      mcScdid: "VB05",
      sector: "FMCG",
    },
    {
      symbol: "VIPIND",
      mcScid: "VIP",
      mcScdid: "VIP",
      sector: "FMCG",
    },
    {
      symbol: "GODREJCP",
      mcScid: "GCP",
      mcScdid: "GCP",
      sector: "FMCG",
    },
    {
      symbol: "DABUR",
      mcScid: "DI",
      mcScdid: "DI",
      angelName: "DABUR INDIA",
      sector: "FMCG",
    },
    {
      symbol: "TATACONSUM",
      mcScid: "TT",
      mcScdid: "TT",
      sector: "FMCG",
    },
    {
      symbol: "MARICO",
      mcScid: "MI25",
      mcScdid: "M13",
      sector: "FMCG",
    },
    {
      symbol: "MCDOWELL-N",
      mcScid: "MC08",
      mcScdid: "US",
      sector: "FMCG",
    },
    {
      symbol: "PGHH",
      mcScid: "PGI",
      mcScdid: "PGH",
      sector: "FMCG",

      angelName: "Procter & Gamble Hygiene & Health Care",
    },
    {
      symbol: "COLPAL",
      mcScid: "CPI",
      mcScdid: "CPI",
      angelName: "COLGATE PALMOLIVE LTD.",
      sector: "FMCG",
    },
    {
      symbol: "PATANJALI",
      mcScid: "RSI",
      mcScdid: "RSI",
      sector: "FMCG",
    },
    {
      symbol: "UBL",
      mcScid: "UBB",
      mcScdid: "UB02",
      sector: "FMCG",
    },
    {
      symbol: "JUBLFOOD",
      mcScid: "JF04",
      mcScdid: "JF04",
      sector: "FMCG",
    },
    {
      symbol: "KRBL",
      mcScid: "KRB",
      mcScdid: "FMCG",
    },
    {
      symbol: "DEVYANI",
      mcScid: "DI23",
      mcScdid: "DI06",
      sector: "FMCG",
    },
    {
      symbol: "HATSUN",
      mcScid: "HAP",
      mcScdid: "HAP",
      sector: "FMCG",
    },
    {
      symbol: "EMAMILTD",
      mcScid: "E05",
      mcScdid: "E06",
      sector: "FMCG",
    },
    {
      symbol: "RADICO",
      mcScid: "RK01",
      mcScdid: "RK01",
      sector: "FMCG",
    },
    {
      symbol: "GILLETTE",
      mcScid: "ISP",
      mcScdid: "GI22",
      angelName: "GILLETTE INDIA",
      sector: "FMCG",
    },
    {
      symbol: "SFL",
      mcScid: "SF30",
      mcScdid: "SF14",
      sector: "FMCG",
    },
    {
      symbol: "BIKAJI",
      mcScid: "BFI01",
      mcScdid: "BFI01",
      sector: "FMCG",
    },
    {
      symbol: "ZYDUSWELL",
      mcScid: "CNA",
      mcScdid: "ZW01",
      sector: "FMCG",
    },
    {
      symbol: "SAPPHIRE",
      mcScid: "SFI05",
      mcScdid: "SFI05",
      sector: "FMCG",
    },
    {
      symbol: "SUNPHARMA",
      mcScid: "SPI",
      mcScdid: "SPI",
      sector: "Healthcare",
    },
    {
      symbol: "METROPOLIS",
      mcScid: "MH09",
      mcScdid: "MH06",
      sector: "Healthcare",
    },
    {
      symbol: "SPARC",
      mcScid: "SPA",
      mcScdid: "SPA",
      angelName: "Sun Pharma Advanced Research Company Ltd",
      sector: "Healthcare",
    },
    {
      symbol: "DIVISLAB",
      mcScid: "DL03",
      mcScdid: "DL03",
      sector: "Healthcare",
    },
    {
      symbol: "CIPLA",
      mcScid: "C",
      mcScdid: "C",
      sector: "Healthcare",
    },
    {
      symbol: "DRREDDY",
      mcScid: "DRL",
      mcScdid: "DRL",
      sector: "Healthcare",
    },
    {
      symbol: "APOLLOHOSP",
      mcScid: "AHE",
      mcScdid: "AHE",
      sector: "Healthcare",
    },
    {
      symbol: "TORNTPHARM",
      mcScid: "TP06",
      mcScdid: "TP06",
      sector: "Healthcare",
    },
    {
      symbol: "MANKIND",
      mcScid: "MP21",
      mcScdid: "MP22",
      sector: "Healthcare",
    },
    {
      symbol: "ZYDUSLIFE",
      mcScid: "CHC",
      mcScdid: "CHC",
      sector: "Healthcare",
    },
    {
      symbol: "MAXHEALTH",
      mcScid: "MHI",
      mcScdid: "MHI",
      sector: "Healthcare",
    },
    {
      symbol: "ABBOTINDIA",
      mcScid: "KP",
      mcScdid: "AI51",
      sector: "Healthcare",
    },
    {
      symbol: "ALKEM",
      mcScid: "AL16",
      mcScdid: "AL05",
      sector: "Healthcare",
    },
    {
      symbol: "AUROPHARMA",
      mcScid: "AP",
      mcScdid: "AP",
      sector: "Healthcare",
    },
    {
      symbol: "LUPIN",
      mcScid: "LC03",
      mcScdid: "L",
      sector: "Healthcare",
    },
    {
      symbol: "BIOCON",
      mcScid: "BL03",
      mcScdid: "BL03",
      sector: "Healthcare",
    },
    {
      symbol: "GLAXO",
      mcScid: "GI",
      mcScdid: "GSK",
      angelName: "GLAXOSMI",
      sector: "Healthcare",
    },
    {
      symbol: "FORTIS",
      mcScid: "FH",
      mcScdid: "FH",
      sector: "Healthcare",
    },
    {
      symbol: "NH",
      mcScid: "NH",
      mcScdid: "NH",
      sector: "Healthcare",
    },

    {
      symbol: "LAURUSLABS",
      mcScid: "LL06",
      mcScdid: "LL05",
      sector: "Healthcare",
    },
    {
      symbol: "IPCALAB",
      mcScid: "IL",
      mcScdid: "IL",
      sector: "Healthcare",
    },
    {
      symbol: "PFIZER",
      mcScid: "P",
      mcScdid: "P",
      angelName: "PFIZER",
      sector: "Healthcare",
    },
    {
      symbol: "AJANTPHARM",
      mcScid: "AP22",
      mcScdid: "AP22",
      sector: "Healthcare",
    },
    {
      symbol: "GLENMARK",
      mcScid: "GP08",
      mcScdid: "GP08",
      sector: "Healthcare",
    },
    {
      symbol: "LALPATHLAB",
      mcScid: "DLP01",
      mcScdid: "DLP01",
      sector: "Healthcare",
    },
    {
      symbol: "SANOFI",
      mcScid: "HMR",
      mcScdid: "AP26",
      angelName: "SANOFI INDIA",
      sector: "Healthcare",
    },
    {
      symbol: "JBCHEPHARM",
      mcScid: "JBC",
      mcScdid: "JBC01",
      sector: "Healthcare",
    },

    {
      symbol: "MEDANTA",
      mcScid: "GH03",
      mcScdid: "GH03",
      sector: "Healthcare",
    },
    {
      symbol: "GLAND",
      mcScid: "GP14",
      mcScdid: "GP14",
      sector: "Healthcare",
    },
    {
      symbol: "ASTERDM",
      mcScid: "ADH",
      mcScdid: "ADH",
      sector: "Healthcare",
    },
    {
      symbol: "KIMS",
      mcScid: "KIO01",
      mcScdid: "KIo01",
      sector: "Healthcare",
    },
    {
      symbol: "SUVENPHAR",
      mcScid: "SP42",
      mcScdid: "SP19",
      sector: "Healthcare",
    },
    {
      symbol: "NATCOPHARM",
      mcScid: "NP01",
      mcScdid: "NP07",
      sector: "Healthcare",
    },
    {
      symbol: "APLLTD",
      mcScid: "AP29",
      mcScdid: "AP35",
      angelName: "ALEMBIC PHARMA",
      sector: "Healthcare",
    },
    {
      symbol: "PPLPHARMA",
      mcScid: "PP37",
      mcScdid: "PP34",
      sector: "Healthcare",
    },
    {
      symbol: "MEDPLUS",
      mcScid: "MHS01",
      mcScdid: "MHS01",
      sector: "Healthcare",
    },
    {
      symbol: "RAINBOW",
      mcScid: "RCM03",
      mcScdid: "RCM03",
      sector: "Healthcare",
    },
    {
      symbol: "POLYMED",
      mcScid: "PM06",
      mcScdid: "PM06",
      sector: "Healthcare",
    },
    {
      symbol: "PGHL",
      mcScid: "EMI",
      mcScdid: "M12",
      angelName: "Procter & Gamble Health Ltd",
      sector: "Healthcare",
    },
    {
      symbol: "WOCKPHARMA",
      mcScid: "W05",
      mcScdid: "W05",
      angelName: "WOCKHARDT",
    },
    {
      symbol: "INDIGO",
      mcScid: "IA05",
      mcScdid: "IA04",
      sector: "Hospitality Travel",
    },
    {
      symbol: "INDHOTEL",
      mcScid: "IHC",
      mcScdid: "IHC",
      sector: "Hospitality Travel",
    },
    {
      symbol: "IRCTC",
      mcScid: "IRC",
      mcScdid: "IRC",
      sector: "Hospitality Travel",
    },
    {
      symbol: "EIHOTEL",
      mcScid: "EIH",
      mcScdid: "EIH",
      sector: "Hospitality Travel",
    },
    {
      symbol: "WESTLIFE",
      mcScid: "DIC",
      mcScdid: "DIC",
      sector: "Hospitality Travel",
    },
    {
      symbol: "CHALET",
      mcScid: "CH03",
      mcScdid: "CH03",
      sector: "Hospitality Travel",
    },
    {
      symbol: "SIEMENS",
      mcScid: "S",
      mcScdid: "S",
      sector: "Industrial Products",
    },

    {
      symbol: "ABB",
      mcScid: "ABB",
      mcScdid: "ABB",
      sector: "Industrial Products",
    },
    {
      symbol: "BEL",
      mcScid: "BE03",
      mcScdid: "BE03",
      sector: "Industrial Products",
    },
    {
      symbol: "HAVELLS",
      mcScid: "HI01",
      mcScdid: "HI01",
      sector: "Industrial Products",
    },
    {
      symbol: "CGPOWER",
      mcScid: "CG",
      mcScdid: "CG",
      sector: "Industrial Products",
    },
    {
      symbol: "BHEL",
      mcScid: "BHE",
      mcScdid: "BHE",
      angelName: "B H E L",
      sector: "Industrial Products",
    },
    {
      symbol: "THERMAX",
      mcScid: "T",
      mcScdid: "T",
      sector: "Industrial Products",
    },
    {
      symbol: "ELGIEQUIP",
      mcScid: "EE01",
      mcScdid: "EE01",
      sector: "Industrial Products",
    },
    {
      symbol: "POWERINDIA",
      mcScid: "APP03",
      mcScdid: "APP03",
      sector: "Industrial Products",
    },
    {
      symbol: "RHIM",
      mcScid: "OR01",
      mcScdid: "OR01",
      sector: "Industrial Products",
    },
    {
      symbol: "SUZLON",
      mcScid: "SE17",
      mcScdid: "SE17",
      sector: "Industrial Products",
    },
    {
      symbol: "TRITURBINE",
      mcScid: "TT12",
      mcScdid: "TT14",
      sector: "Industrial Products",
    },
    {
      symbol: "VGUARD",
      mcScid: "VI16",
      mcScdid: "VI02",
      sector: "Industrial Products",
    },
    {
      symbol: "APARINDS",
      mcScid: "AI40",
      mcScdid: "AI40",
      sector: "Industrial Products",
    },
    {
      symbol: "DATAPATTNS",
      mcScid: "DPI01",
      mcScdid: "DPI01",
      sector: "Industrial Products",
    },
    {
      symbol: "CRAFTSMAN",
      mcScid: "CA07",
      mcScdid: "CA04",
      sector: "Industrial Products",
    },
    {
      symbol: "KAYNES",
      mcScid: "KTI05",
      mcScdid: "KTI",
      sector: "Industrial Products",
    },
    {
      symbol: "KSB",
      mcScid: "KSB",
      mcScdid: "KSB",
      sector: "Industrial Products",
    },
    {
      symbol: "LT",
      mcScid: "LT",
      mcScdid: "LT",
      sector: "Industries",
    },
    {
      symbol: "DLF",
      mcScid: "D04",
      mcScdid: "D04",
      sector: "Industries",
    },
    {
      symbol: "HAL",
      mcScid: "HAL",
      mcScdid: "HAL",
      sector: "Industries",
    },
    {
      symbol: "LODHA",
      mcScid: "MD04",
      mcScdid: "MD03",
      sector: "Industries",
    },
    {
      symbol: "CUMMINSIND",
      mcScid: "CI02",
      mcScdid: "CI02",
      sector: "Industries",
    },
    {
      symbol: "GODREJPROP",
      mcScid: "GP11",
      mcScdid: "GP11",
      sector: "Industries",
    },
    {
      symbol: "OBEROIRLTY",
      mcScid: "OR",
      mcScdid: "OR",
      sector: "Industries",
    },
    {
      symbol: "PHOENIXLTD",
      mcScid: "PM02",
      mcScdid: "PM02",
      sector: "Industries",
    },
    {
      symbol: "GMRINFRA",
      mcScid: "GI27",
      mcScdid: "GI27",
      sector: "Industries",
    },
    {
      symbol: "RVNL",
      mcScid: "RVN",
      mcScdid: "RVN",
      angelName: "Rail Vikas",
      sector: "Industries",
    },
    {
      symbol: "BDL",
      mcScid: "BDL01",
      mcScdid: "BDL01",
      sector: "Industries",
    },
    {
      symbol: "PRESTIGE",
      mcScid: "PEP02",
      mcScdid: "PEP02",
      sector: "Industries",
    },
    {
      symbol: "MAZDOCK",
      mcScid: "MDS01",
      mcScdid: "MDS01",
      sector: "Industries",
    },
    {
      symbol: "IRB",
      mcScid: "IID01",
      mcScdid: "IID01",
      sector: "Industries",
    },
    {
      symbol: "KEC",
      mcScid: "KEC03",
      mcScdid: "KEC04",
      sector: "Industries",
    },
    {
      symbol: "BRIGADE",
      mcScid: "BE08",
      mcScdid: "BE08",
      sector: "Industries",
    },
    {
      symbol: "GRINFRA",
      mcScid: "I13",
      mcScdid: "I09",
      sector: "Industries",
    },
    {
      symbol: "RITES",
      mcScid: "R06",
      mcScdid: "R02",
      sector: "Industries",
    },

    {
      symbol: "PNCINFRA",
      mcScid: "PI29",
      mcScdid: "PI26",
      sector: "Industries",
    },
    {
      symbol: "NCC",
      mcScid: "NCC01",
      mcScdid: "NCC01",
      sector: "Industries",
    },
    {
      symbol: "NBCC",
      mcScid: "NBC",
      mcScdid: "NBC01",
      sector: "Industries",
    },
    {
      symbol: "TCS",
      mcScid: "TCS",
      mcScdid: "TCS",
      angelName: "TCS",
      sector: "IT Industry",
    },
    {
      symbol: "INFY",
      mcScid: "IT",
      mcScdid: "IT",
      angelName: "INFOSYS",
      sector: "IT Industry",
    },
    {
      symbol: "HCLTECH",
      mcScid: "HCL02",
      mcScdid: "HCL02",
      sector: "IT Industry",
    },

    {
      symbol: "WIPRO",
      mcScid: "W",
      mcScdid: "W",
      sector: "IT Industry",
    },
    {
      symbol: "LTIM",
      mcScid: "LI09",
      mcScdid: "LI12",
      sector: "IT Industry",
    },
    {
      symbol: "TECHM",
      mcScid: "TM4",
      mcScdid: "TM4",
      angelName: "TECH MAHINDRA",
      sector: "IT Industry",
    },
    {
      symbol: "NAUKRI",
      mcScid: "IEI01",
      mcScdid: "IEI01",
      sector: "IT Industry",
    },
    {
      symbol: "TATAELXSI",
      mcScid: "TEI",
      mcScdid: "TE",
      sector: "IT Industry",
    },
    {
      symbol: "LTTS",
      mcScid: "LTS",
      mcScdid: "LTS",
      sector: "IT Industry",
    },
    {
      symbol: "PERSISTENT",
      mcScid: "PS15",
      mcScdid: "PS15",
      sector: "IT Industry",
    },
    {
      symbol: "MPHASIS",
      mcScid: "BFL",
      mcScdid: "MB02",
      sector: "IT Industry",
    },
    {
      symbol: "OFSS",
      mcScid: "S11",
      mcScdid: "OFS01",
      sector: "IT Industry",
    },
    {
      symbol: "KPITTECH",
      mcScid: "KPITT54265",
      mcScdid: "KPITT54265",
      sector: "IT Industry",
    },
    {
      symbol: "COFORGE",
      mcScid: "NII02",
      mcScdid: "NII02",
      sector: "IT Industry",
    },
    {
      symbol: "CYIENT",
      mcScid: "IE07",
      mcScdid: "IE07",
      sector: "IT Industry",
    },
    {
      symbol: "SONATSOFTW",
      mcScid: "SS42",
      mcScdid: "SS42",
      sector: "IT Industry",
    },
    {
      symbol: "HAPPSTMNDS",
      mcScid: "HMT01",
      mcScdid: "HMT01",
      sector: "IT Industry",
    },
    {
      symbol: "AFFLE",
      mcScid: "AI72",
      mcScdid: "AI82",
      sector: "IT Industry",
    },
    {
      symbol: "TEJASNET",
      mcScid: "TN",
      mcScdid: "TN",
      sector: "IT Industry",
    },
    {
      symbol: "CAMS",
      mcScid: "CAM",
      mcScdid: "CAM",
      sector: "IT Industry",
    },
    {
      symbol: "TANLA",
      mcScid: "TS11",
      mcScdid: "TS11",
      sector: "IT Industry",
    },
    {
      symbol: "BSOFT",
      mcScid: "KPI01",
      mcScdid: "KPI02",
      sector: "IT Industry",
    },
    {
      symbol: "ADANIPORTS",
      mcScid: "MPS",
      mcScdid: "MPS",
      angelName: "ADANI PORTS",
      sector: "Logistics Freight",
    },
    {
      symbol: "GPPL",
      mcScid: "GPP03",
      mcScdid: "GPP03",
      angelName: "GUJURAT PIPAVAV",
      sector: "Logistics Freight",
    },
    {
      symbol: "CONCOR",
      mcScid: "CCI",
      mcScdid: "CCI",
      sector: "Logistics Freight",
    },
    {
      symbol: "DELHIVERY",
      mcScid: "D05",
      mcScdid: "D06",
      sector: "Logistics Freight",
    },
    {
      symbol: "BLUEDART",
      mcScid: "BDE",
      mcScdid: "BDE",
      sector: "Logistics Freight",
    },
    {
      symbol: "AEGISCHEM",
      mcScid: "AC02",
      mcScdid: "AL9",
      angelName: "AEGIS LOGISTICS",
      sector: "Logistics Freight",
    },
    {
      symbol: "GESHIP",
      mcScid: "GES",
      mcScdid: "GES",
      sector: "Logistics Freight",
    },
    {
      symbol: "GRASIM",
      mcScid: "GI01",
      mcScdid: "GI01",
      sector: "Others",
    },

    {
      symbol: "SRF",
      mcScid: "SRF",
      mcScdid: "SRF",
      sector: "Others",
    },
    {
      symbol: "3MINDIA",
      mcScid: "B3M",
      mcScdid: "MI42",
      sector: "Others",
    },
    {
      symbol: "SYNGENE",
      mcScid: "SI62",
      mcScdid: "SI10",
      sector: "Others",
    },
    {
      symbol: "DCMSHRIRAM",
      mcScid: "DCM02",
      mcScdid: "DCM02",
      sector: "Others",
    },
    {
      symbol: "BIRLACORPN",
      mcScid: "BC07",
      mcScdid: "BC07",
      sector: "Others",
    },
    {
      symbol: "CENTURYTEX",
      mcScid: "CTI",
      mcScdid: "CTI",
      sector: "Others",
    },
    {
      symbol: "ULTRACEMCO",
      mcScid: "UTC",
      mcScdid: "UTC01",
      sector: "Raw Materials",
    },
    {
      symbol: "COALINDIA",
      mcScid: "CI29",
      mcScdid: "CI11",
      sector: "Raw Materials",
    },
    {
      symbol: "PIDILITIND",
      mcScid: "PI11",
      mcScdid: "PI11",
      sector: "Raw Materials",
    },
    {
      symbol: "HINDZINC",
      mcScid: "HZ",
      mcScdid: "HZ",
      sector: "Raw Materials",
    },
    {
      symbol: "VEDL",
      mcScid: "SG",
      mcScdid: "SG",
      sector: "Raw Materials",
    },
    {
      symbol: "HINDALCO",
      mcScid: "H",
      mcScdid: "HI",
      angelName: "Hindalco Industries Ltd",
      sector: "Raw Materials",
    },

    {
      symbol: "SHREECEM",
      mcScid: "SC12",
      mcScdid: "SC12",
      sector: "Raw Materials",
    },
    {
      symbol: "AMBUJACEM",
      mcScid: "GAC",
      mcScdid: "AC18",
      sector: "Raw Materials",
    },
    {
      symbol: "JINDALSTEL",
      mcScid: "JSP",
      mcScdid: "JSP",
      sector: "Raw Materials",
    },
    {
      symbol: "DALBHARAT",
      mcScid: "OCL",
      mcScdid: "OCL",
      sector: "Raw Materials",
    },
    {
      symbol: "FLUOROCHEM",
      mcScid: "GUJAR54281",
      mcScdid: "GUJAR54281",
      sector: "Raw Materials",
    },
    {
      symbol: "SOLARINDS",
      mcScid: "SE20",
      mcScdid: "SII04",
      sector: "Raw Materials",
    },
    {
      symbol: "ACC",
      mcScid: "ACC",
      mcScdid: "ACC06",
      sector: "Raw Materials",
    },
    {
      symbol: "NMDC",
      mcScid: "NMD01",
      mcScdid: "NMD02",
      sector: "Raw Materials",
    },
    {
      symbol: "DEEPAKNTR",
      mcScid: "DN",
      mcScdid: "DN",
      sector: "Raw Materials",
    },
    {
      symbol: "TATACHEM",
      mcScid: "TC",
      mcScdid: "TC",
      sector: "Raw Materials",
    },
    {
      symbol: "JKCEMENT",
      mcScid: "JKC03",
      mcScdid: "JKC03",
      sector: "Raw Materials",
    },
    {
      symbol: "NAVINFLUOR",
      mcScid: "PRC",
      mcScdid: "NFI",
      sector: "Raw Materials",
    },
    {
      symbol: "RAMCOCEM",
      mcScid: "MC",
      mcScdid: "MC",
      sector: "Raw Materials",
    },
    {
      symbol: "ATUL",
      mcScid: "A06",
      mcScdid: "A06",
      sector: "Raw Materials",
    },
    {
      symbol: "VINATIORGA",
      mcScid: "VO01",
      mcScdid: "VO01",
      sector: "Raw Materials",
    },
    {
      symbol: "AARTIIND",
      mcScid: "AI",
      mcScdid: "AI45",
      sector: "Raw Materials",
    },
    {
      symbol: "GODREJIND",
      mcScid: "GS",
      mcScdid: "GI23",
      sector: "Raw Materials",
    },
    {
      symbol: "CLEAN",
      mcScid: "CST",
      mcScdid: "CST",
      sector: "Raw Materials",
    },
    {
      symbol: "FINEORG",
      mcScid: "FOI",
      mcScdid: "FOI",
      sector: "Raw Materials",
    },
    {
      symbol: "NUVOCO",
      mcScid: "NVC",
      mcScdid: "NVC",
      sector: "Raw Materials",
    },
    {
      symbol: "ALKYLAMINE",
      mcScid: "AAC",
      mcScdid: "AAC",
      sector: "Raw Materials",
    },
    {
      symbol: "ANURAS",
      mcScid: "ARI02",
      mcScdid: "ARI02",
      sector: "Raw Materials",
    },
    {
      symbol: "KIOCL",
      mcScid: "KIO",
      mcScdid: "KIO",
      sector: "Raw Materials",
    },
    {
      symbol: "AETHER",
      mcScid: "AI74",
      mcScdid: "AI84",
      sector: "Raw Materials",
    },
    {
      symbol: "HINDCOPPER",
      mcScid: "HC07",
      mcScdid: "HC07",
      angelName: "HINDUSTAN COPP..",
      sector: "Raw Materials",
    },
    {
      symbol: "JKLAKSHMI",
      mcScid: "JKC",
      mcScdid: "JKL01",
      sector: "Raw Materials",
    },
    {
      symbol: "BHARTIARTL",
      mcScid: "BTV",
      mcScdid: "BA08",
      sector: "Tele Communication",
    },
    {
      symbol: "POLYCAB",
      mcScid: "PI41",
      mcScdid: "PI44",
      sector: "Tele Communication",
    },
    {
      symbol: "INDUSTOWER",
      mcScid: "BI26",
      mcScdid: "BI14",
      sector: "Tele Communication",
    },
    {
      symbol: "TATACOMM",
      mcScid: "VSN",
      mcScdid: "TC17",
      sector: "Tele Communication",
    },
    {
      symbol: "IDEA",
      mcScid: "IC8",
      mcScdid: "IC8",
      sector: "Tele Communication",
    },
    {
      symbol: "KEI",
      mcScid: "KEI",
      mcScdid: "KEI",
      sector: "Tele Communication",
    },
    {
      symbol: "TTML",
      mcScid: "HTC02",
      mcScdid: "TTM01",
      sector: "Tele Communication",
    },
    {
      symbol: "FINCABLES",
      mcScid: "FC01",
      mcScdid: "FC01",
      sector: "Tele Communication",
    },
    {
      symbol: "ITI",
      mcScid: "ITI",
      mcScdid: "ITI",
      sector: "Tele Communication",
    },
    {
      symbol: "HFCL",
      mcScid: "HFC",
      mcScdid: "HFC",
      sector: "Tele Communication",
    },
    {
      symbol: "KPIL",
      mcScid: "KPT",
      mcScdid: "KPT",
      sector: "Tele Communication",
    },
    {
      symbol: "STLTECH",
      mcScid: "SO03",
      mcScdid: "ST20",
      angelName: "STERLITE TECH.",
      sector: "Tele Communication",
    },
    {
      symbol: "PAGEIND",
      mcScid: "PI35",
      mcScdid: "PI35",
      sector: "Textile Industry",
    },
    {
      symbol: "MANYAVAR",
      mcScid: "VF10",
      mcScdid: "VF04",
      sector: "Textile Industry",
    },
    {
      symbol: "KPRMILL",
      mcScid: "M09",
      mcScdid: "M15",
      sector: "Textile Industry",
    },
    {
      symbol: "TRIDENT",
      mcScid: "AI01",
      mcScdid: "AI01",
      sector: "Textile Industry",
    },
    {
      symbol: "LAXMIMACH",
      mcScid: "LMW",
      mcScdid: "LMW",
      sector: "Textile Industry",
    },
    {
      symbol: "RAYMOND",
      mcScid: "R",
      mcScdid: "R",
      sector: "Textile Industry",
    },
    {
      symbol: "VTL",
      mcScid: "MSM",
      mcScdid: "VT10",
      sector: "Textile Industry",
    },
    {
      symbol: "WELSPUNIND",
      mcScid: "WI03",
      mcScdid: "WI03",
      angelName: "Welspun India Ltd.",
      sector: "Textile Industry",
    },
    {
      symbol: "SWANENERGY",
      mcScid: "SM09",
      mcScdid: "SM09",
      sector: "Textile Industry",
    },
    {
      symbol: "COCHINSHIP",
      mcScid: "CS17",
      mcScdid: "CS",
      sector: "Ship Building",
    },
    {
      symbol: "EIDPARRY",
      mcScid: "EID",
      mcScdid: "EID",
      sector: "Sugar",
    },
    {
      symbol: "EPL",
      mcScid: "EP",
      mcScdid: "EP11",
      angelName: "EPL LTD",
      sector: "Packaging Materials-Plastic Products",
    },
    {
      symbol: "GALAXYSURF",
      mcScid: "GSL06",
      mcScdid: "GSL06",
      sector: "Diversified Chemicals",
    },
    {
      symbol: "MMTC",
      mcScid: "MMT",
      mcScdid: "MMT",
      sector: "Trading",
    },
    {
      symbol: "PAYTM",
      mcScid: "OC10",
      mcScdid: "OC03",
      angelName: "ONE 97",
      sector: "Online Services",
    },

    {
      symbol: "SYMPHONY",
      mcScid: "SCS04",
      mcScdid: "SCS04",
      sector: "Domestic Appliances",
    },
    {
      symbol: "JIOFIN",
      mcScid: "JFS",
      mcScdid: "JFS",
      angelName: "Jio Financial Services",
      sector: "Finance - Others",
    },
  ],
};
